# Generated by Django 4.2.3 on 2023-07-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_register_user_oauth_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Design', 'Design')], default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='track',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='univ',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
